[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# adjust default size
# dimensions = {columns = 250, lines = 75}

# decorations = "Buttonless"
# Windows and Linux I use 1 for opacity but use less depending on choice
opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "FiraMono Nerd Font"
# FiraCode Nerd Font Mono
size = 18